roxannecvl/whokipedia

model/GameModel.ts
model/HintList.ts
model/resolvePromise.ts
pages/example.vue
views/infoboxView.vue

Create a v1 version of GameModel 

---

package.json
pages/index.vue

Fix bad merge conflicts resolution

---

model/UserModel.ts
package.json
pages/index.vue
pages/statistics.vue
utilities/Utils.ts
views/statisticsView.vue

Click on "Test the statistics" to display the user's stats (only when logged in).
I used [vue-chartjs](https://vue-chartjs.org/guide/), the wrapper for [Chart.js](https://github.com/chartjs/Chart.js) in Vue, to display the number of guesses, the time and the rank over the days.

User model v1

---

app.vue
pages/daily-challenge.vue

This PR add responsive to the app to make it usable on mobile.
Game :
Content of the slideover:
Closes #49 
Closes #50 
Closes #51

Make the app responsive

---

app.vue
pages/index.vue
presenters/WelcomePagePresenter.vue
views/SidebarView.vue
views/WelcomePageView.vue

Created a presenter and a view
The presenter is now called in index.vue
Closes #66

Created the welcome page (based on Figma) 

---

views/WelcomePageView.vue

 Hydration style mismatch error fixed (#71)

---

model/FirebaseModel.ts
presenters/LoginSignupPresenter.vue

Fix user persistence

---

model/FirebaseModel.ts
package.json
presenters/LoginSignupPresenter.vue
utilities/Utils.ts
views/LoginView.vue
views/SignupView.vue
views/StatisticsView.vue

Add username feature to the authentication process

---

model/GameModel.ts
presenters/GamePresenter.vue
presenters/SidebarPresenter.vue
presenters/StatisticsPresenter.vue
utilities/Utils.ts
views/GameCenterView.vue
views/InfoboxView.vue
views/LoginView.vue
views/SidebarView.vue
views/SignupView.vue
views/StatisticsView.vue
views/WelcomePageView.vue

This PR adds blurring to names in paragraphs during the game, and removes line breaks so that they are contiguous. 
Closes #78

Improve paragraphs display

---

presenters/GamePresenter.vue
presenters/LoginSignupPresenter.vue
views/LoginSignupView.vue
views/SearchFieldView.vue

Refactor : Removed UI from presenters 

---

app.vue
model/FirebaseModel.ts
model/UserModel.ts
pages/daily-challenge.vue
presenters/GamePresenter.vue
presenters/LeaderboardPresenter.vue
presenters/StatisticsPresenter.vue
utilities/Utils.ts
views/LeaderboardView.vue
views/StatisticsView.vue

Persist game model and update user's stats at the end of a game

---

model/GameModel.ts
model/Hint.ts
package.json
pages/daily-challenge.vue
presenters/GamePresenter.vue
server/api/blur-image.ts
views/GameCenterView.vue
views/InfoboxView.vue

Add an API to get blurred images encoded in base64 

---

model/FirebaseModel.ts
presenters/GamePresenter.vue
presenters/HeaderPresenter.vue
views/LeaderboardView.vue

style to leaderboard, averageRank gets updated if rank updated, averageRank rounded in leaderboardView

---

model/FirebaseModel.ts
model/GameModel.ts
model/Hint.ts
pages/daily-challenge.vue
presenters/GamePresenter.vue
utilities/Utils.ts

Fixed issue when several accounts connecting to daily challenge back to back

---

api/Parsing.ts
api/WikipediaSource.ts
model/CelebrityList.ts
model/FirebaseModel.ts
model/GameModel.ts
model/Hint.ts
model/UserModel.ts
pages/daily-challenge.vue
pages/index.vue
pages/test.vue
presenters/GamePresenter.vue
presenters/HeaderPresenter.vue
presenters/SidebarPresenter.vue
presenters/WelcomePagePresenter.vue
utilities/Utils.ts
views/GameCenterView.vue
views/HeaderView.vue
views/InfoboxView.vue
views/LeaderboardView.vue
views/LoginSignupView.vue
views/SearchFieldView.vue
views/ShouldLoginView.vue
views/SidebarView.vue
views/StatisticsView.vue
views/WelcomePageView.vue

This PR removes all non-needed semicolons `;` to comply with what we agreed on during last meeting. 
closes #118

Remove all non needed semicolons

---

pages/daily-challenge.vue
pages/solo-mode.vue

Fix double scroll on small screens

---

model/FirebaseModel.ts
model/GameModel.ts
pages/daily-challenge.vue
pages/solo-mode.vue
presenters/GamePresenter.vue
presenters/HeaderPresenter.vue
presenters/PlayAgainPresenter.vue
utilities/Utils.ts

The users settings do not influence the timestamp anymore, this reduces risk of cheating and/or bugs 
closes #126

Timestamp is consistent 

---

model/FirebaseModel.ts
model/GameModel.ts
model/UserModel.ts
pages/daily-challenge.vue
pages/solo-mode.vue
presenters/GamePresenter.vue
presenters/HeaderPresenter.vue
presenters/PlayAgainPresenter.vue
utilities/Utils.ts
views/HeaderView.vue
views/LeaderboardView.vue
views/SidebarView.vue
views/StatisticsView.vue

Leaderboard and Statistics UI improved 

---

model/GameModel.ts
views/HeaderView.vue
views/StatisticsView.vue

fix : no more freeze on lose

---

model/GameModel.ts
model/Hint.ts

they are now part of the state and calculated in init this solved our problem
closes #134

Remove getters in model/GameModel.ts as not needed 

---

app.vue
model/FirebaseModel.ts
model/GameModel.ts
model/UserModel.ts
pages/daily-challenge.vue
pages/solo-mode.vue
pages/test.vue
presenters/GamePresenter.vue
presenters/HeaderPresenter.vue
presenters/PlayAgainPresenter.vue
utilities/Utils.ts
views/LeaderboardView.vue
views/LoginSignupView.vue
views/SearchFieldView.vue
views/StatisticsView.vue

This PR fixes UTC dates problem (different time zones leaded to different celebrities).
It also adds much documentation, types and refactors some code to lighten the code base. 
It also changes error messages upon signup, login and logout to something more user-friendly. 
Finally, it adds a small 1px margin to the search bar to solve a bug in which search bar melted in header.
Closes #139 
Closes #138

Fix date issues, improve error messages, fix reloading mess and add documentation

---

model/Hint.ts
pages/daily-challenge.vue
presenters/HeaderPresenter.vue
server/api/blur-image.ts
views/GameCenterView.vue
views/HeaderView.vue
views/InfoboxView.vue
views/LeaderboardView.vue

This PR is a tiny refactor only adding some comments and removing useless lines from the code.

Small refactor adding comments

---

model/FirebaseModel.ts
utilities/Auth.ts

This PR assures uniqueness of usernames when a new account is created

---

pages/daily-challenge.vue
pages/solo-mode.vue

Corrected timer bug on reload 

---

pages/solo-mode.vue

I had forgotten to apply my changes on the `PlayAgainPresenter` for both mobile devices and desktop. This PR brings a fix.

Small fix about latest PR
